package com.simon.hellomaterial;

import android.app.Activity;
import android.os.Bundle;
import android.support.v7.widget.DefaultItemAnimator;
import android.support.v7.widget.LinearLayoutManager;
import android.support.v7.widget.RecyclerView;
import android.widget.ImageView;

/**
 * Created by ehs_Simon on 2016/1/14.
 */
public class FirstActivity extends Activity {
    private ImageView placeImage;
    private int[] imgSmall = {
            R.drawable.android_s,
            R.drawable.android_s,
            R.drawable.android_s,
            R.drawable.android_s,
            R.drawable.android_s
    };
    // this is data fro recycler view
    ItemData itemsData[] = {
            new ItemData("Delete", imgSmall[0]),
            new ItemData("Cloud", imgSmall[1]),
            new ItemData("Favorite", imgSmall[2]),
            new ItemData("Like", imgSmall[3]),
            new ItemData("Rating", imgSmall[4]),
            new ItemData("Delete", imgSmall[0]),
            new ItemData("Cloud", imgSmall[1]),
            new ItemData("Favorite", imgSmall[2]),
            new ItemData("Like", imgSmall[3]),
            new ItemData("Rating", imgSmall[4]),
            new ItemData("Delete", imgSmall[0]),
            new ItemData("Cloud", imgSmall[1]),
            new ItemData("Favorite", imgSmall[2]),
            new ItemData("Like", imgSmall[3]),
            new ItemData("Rating", imgSmall[4]),
            new ItemData("Delete", imgSmall[0]),
            new ItemData("Cloud", imgSmall[1]),
            new ItemData("Favorite", imgSmall[2]),
            new ItemData("Like", imgSmall[3]),
            new ItemData("Rating", imgSmall[4]),
            new ItemData("Delete", imgSmall[0]),
            new ItemData("Cloud", imgSmall[1]),
            new ItemData("Favorite", imgSmall[2]),
            new ItemData("Like", imgSmall[3]),
            new ItemData("Rating", imgSmall[4]),
            new ItemData("Delete", imgSmall[0]),
            new ItemData("Cloud", imgSmall[1]),
            new ItemData("Favorite", imgSmall[2]),
            new ItemData("Like", imgSmall[3]),
            new ItemData("Rating", imgSmall[4]),
            new ItemData("Delete", imgSmall[0]),
            new ItemData("Cloud", imgSmall[1]),
            new ItemData("Favorite", imgSmall[2]),
            new ItemData("Like", imgSmall[3]),
            new ItemData("Rating", imgSmall[4]),
            new ItemData("Delete", imgSmall[0]),
            new ItemData("Cloud", imgSmall[1]),
            new ItemData("Favorite", imgSmall[2]),
            new ItemData("Like", imgSmall[3]),
            new ItemData("Rating", imgSmall[4]),
            new ItemData("Delete", imgSmall[0]),
            new ItemData("Cloud", imgSmall[1]),
            new ItemData("Favorite", imgSmall[2]),
            new ItemData("Like", imgSmall[3]),
            new ItemData("Rating", imgSmall[4]),
            new ItemData("Delete", imgSmall[0]),
            new ItemData("Cloud", imgSmall[1]),
            new ItemData("Favorite", imgSmall[2]),
            new ItemData("Like", imgSmall[3]),
            new ItemData("Rating", imgSmall[4]),
            new ItemData("Delete", imgSmall[0]),
            new ItemData("Cloud", imgSmall[1]),
            new ItemData("Favorite", imgSmall[2]),
            new ItemData("Like", imgSmall[3]),
            new ItemData("Rating", imgSmall[4]),
            new ItemData("Delete", imgSmall[0]),
            new ItemData("Cloud", imgSmall[1]),
            new ItemData("Favorite", imgSmall[2]),
            new ItemData("Like", imgSmall[3]),
            new ItemData("Rating", imgSmall[4]),
            new ItemData("Delete", imgSmall[0]),
            new ItemData("Cloud", imgSmall[1]),
            new ItemData("Favorite", imgSmall[2]),
            new ItemData("Like", imgSmall[3]),
            new ItemData("Rating", imgSmall[4]),
            new ItemData("Delete", imgSmall[0]),
            new ItemData("Cloud", imgSmall[1]),
            new ItemData("Favorite", imgSmall[2]),
            new ItemData("Like", imgSmall[3]),
            new ItemData("Rating", imgSmall[4]),
            new ItemData("Delete", imgSmall[0]),
            new ItemData("Cloud", imgSmall[1]),
            new ItemData("Favorite", imgSmall[2]),
            new ItemData("Like", imgSmall[3]),
            new ItemData("Rating", imgSmall[4]),
            new ItemData("Delete", imgSmall[0]),
            new ItemData("Cloud", imgSmall[1]),
            new ItemData("Favorite", imgSmall[2]),
            new ItemData("Like", imgSmall[3]),
            new ItemData("Rating", imgSmall[4]),
            new ItemData("Delete", imgSmall[0]),
            new ItemData("Cloud", imgSmall[1]),
            new ItemData("Favorite", imgSmall[2]),
            new ItemData("Like", imgSmall[3]),
            new ItemData("Rating", imgSmall[4]),
            new ItemData("Delete", imgSmall[0]),
            new ItemData("Cloud", imgSmall[1]),
            new ItemData("Favorite", imgSmall[2]),
            new ItemData("Like", imgSmall[3]),
            new ItemData("Rating", imgSmall[4]),
            new ItemData("Delete", imgSmall[0]),
            new ItemData("Cloud", imgSmall[1]),
            new ItemData("Favorite", imgSmall[2]),
            new ItemData("Like", imgSmall[3]),
            new ItemData("Rating", imgSmall[4]),
            new ItemData("Delete", imgSmall[0]),
            new ItemData("Cloud", imgSmall[1]),
            new ItemData("Favorite", imgSmall[2]),
            new ItemData("Like", imgSmall[3]),
            new ItemData("Rating", imgSmall[4]),
            new ItemData("Delete", imgSmall[0]),
            new ItemData("Cloud", imgSmall[1]),
            new ItemData("Favorite", imgSmall[2]),
            new ItemData("Like", imgSmall[3]),
            new ItemData("Rating", imgSmall[4]),
            new ItemData("Delete", imgSmall[0]),
            new ItemData("Cloud", imgSmall[1]),
            new ItemData("Favorite", imgSmall[2]),
            new ItemData("Like", imgSmall[3]),
            new ItemData("Rating", imgSmall[4]),
            new ItemData("Delete", imgSmall[0]),
            new ItemData("Cloud", imgSmall[1]),
            new ItemData("Favorite", imgSmall[2]),
            new ItemData("Like", imgSmall[3]),
            new ItemData("Rating", imgSmall[4]),
            new ItemData("Delete", imgSmall[0]),
            new ItemData("Cloud", imgSmall[1]),
            new ItemData("Favorite", imgSmall[2]),
            new ItemData("Like", imgSmall[3]),
            new ItemData("Rating", imgSmall[4]),
            new ItemData("Delete", imgSmall[0]),
            new ItemData("Cloud", imgSmall[1]),
            new ItemData("Favorite", imgSmall[2]),
            new ItemData("Like", imgSmall[3]),
            new ItemData("Rating", imgSmall[4]),
            new ItemData("Delete", imgSmall[0]),
            new ItemData("Cloud", imgSmall[1]),
            new ItemData("Favorite", imgSmall[2]),
            new ItemData("Like", imgSmall[3]),
            new ItemData("Rating", imgSmall[4]),
            new ItemData("Delete", imgSmall[0]),
            new ItemData("Cloud", imgSmall[1]),
            new ItemData("Favorite", imgSmall[2]),
            new ItemData("Like", imgSmall[3]),
            new ItemData("Rating", imgSmall[4]),
            new ItemData("Delete", imgSmall[0]),
            new ItemData("Cloud", imgSmall[1]),
            new ItemData("Favorite", imgSmall[2]),
            new ItemData("Like", imgSmall[3]),
            new ItemData("Rating", imgSmall[4]),
            new ItemData("Delete", imgSmall[0]),
            new ItemData("Cloud", imgSmall[1]),
            new ItemData("Favorite", imgSmall[2]),
            new ItemData("Like", imgSmall[3]),
            new ItemData("Rating", imgSmall[4]),
            new ItemData("Delete", imgSmall[0]),
            new ItemData("Cloud", imgSmall[1]),
            new ItemData("Favorite", imgSmall[2]),
            new ItemData("Like", imgSmall[3]),
            new ItemData("Rating", imgSmall[4]),
            new ItemData("Delete", imgSmall[0]),
            new ItemData("Cloud", imgSmall[1]),
            new ItemData("Favorite", imgSmall[2]),
            new ItemData("Like", imgSmall[3]),
            new ItemData("Rating", imgSmall[4]),
            new ItemData("Delete", imgSmall[0]),
            new ItemData("Cloud", imgSmall[1]),
            new ItemData("Favorite", imgSmall[2]),
            new ItemData("Like", imgSmall[3]),
            new ItemData("Rating", imgSmall[4]),
            new ItemData("Delete", imgSmall[0]),
            new ItemData("Cloud", imgSmall[1]),
            new ItemData("Favorite", imgSmall[2]),
            new ItemData("Like", imgSmall[3]),
            new ItemData("Rating", imgSmall[4]),
            new ItemData("Delete", imgSmall[0]),
            new ItemData("Cloud", imgSmall[1]),
            new ItemData("Favorite", imgSmall[2]),
            new ItemData("Like", imgSmall[3]),
            new ItemData("Rating", imgSmall[4]),
            new ItemData("Delete", imgSmall[0]),
            new ItemData("Cloud", imgSmall[1]),
            new ItemData("Favorite", imgSmall[2]),
            new ItemData("Like", imgSmall[3]),
            new ItemData("Rating", imgSmall[4])
    };

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_first);

        RecyclerView recyclerView = (RecyclerView) findViewById(R.id.recycler_view);
        recyclerView.setLayoutManager(new LinearLayoutManager(this));
        MyAdapter mAdapter = new MyAdapter(this, itemsData);
        recyclerView.setAdapter(mAdapter);
        recyclerView.setItemAnimator(new DefaultItemAnimator());

    }
}
